### ISSUE TITLE
removing dev branch

### ISSUE THREAD

**Issue by brimstone** [myzsh/myzsh#57]
What if we removed the dev branch? It looks like we're following a good workflow of making a branch and submitting a PR back to dev. What if we cut out the middle man (dev) and just did this off of master?

Proposed migration steps:
1. Merge the dev branch into master since 0f6f13d broke the straight history.
2. PR for something in `init` that detects the dev branch suggests people checkout master instead.
3. Move the dev pointer up past the dev check PR and leave it there.

Thoughts?

**Comment by dan9186** [comment]
+1 I like it, I've wanted to get rid of dev for a bit now.
