### ISSUE TITLE
Git Push To Master Confirmation

### ISSUE THREAD

**Issue by dan9186** [myzsh/myzsh#81]
I stumbled upon this for some other purposes and wanted to see if there was any interest in some modifications of such a thing for the git module?  I'm thinking of not making it an explicit no, but rather an are you sure sort of thing.

```zsh
#disable git push origin master
git() {
        if [[ $@ == "push origin master" ]];
        then echo "YOU DISABLED THIS REMEMBER?";
        else command git "$@";
        fi;
}
```

**Comment by brimstone** [comment]
I push to master, a lot. Mainly for my own projects. Also, I almost always `git push -u origin master`, so this check wouldn't catch my workflow. I'm not against this being a configurable, but it also needs a better check.

**Comment by dan9186** [comment]
Thinking on this one some more, it's probably best to configure this on a per project basis with pre-commit hooks.  No need for it here if that's the case.  Going to close this for now in favor of that.
